### ISSUE TITLE
Safari 9.0で動かない

### ISSUE THREAD

**Issue by napo0703** [nekobato/GyazzAC#21]
![](https://i.gyazo.com/1bcbb7dfcaf2d9d5c0e69e2e2f69bebc.png)

**Comment by nekobato** [comment]
てゆーかそもそも動かないっぽい

**Comment by nekobato** [comment]
2cf54b9cf61933455c2fa56c0ece47df4f2ca9be で治った
キャッシュがあると思うので一旦シークレットモードで動かしてください @napo0703
